//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldCupWPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorldCupWPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Ball {
            get {
                object obj = ResourceManager.GetObject("Ball", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engleski.
        /// </summary>
        public static string jezikEngleski {
            get {
                return ResourceManager.GetString("jezikEngleski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hrvatski.
        /// </summary>
        public static string jezikHrvatski {
            get {
                return ResourceManager.GetString("jezikHrvatski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da.
        /// </summary>
        public static string kapetanDa {
            get {
                return ResourceManager.GetString("kapetanDa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne.
        /// </summary>
        public static string kapetanNe {
            get {
                return ResourceManager.GetString("kapetanNe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite jezik aplikacije.
        /// </summary>
        public static string pocPostavkeJezikAplikacije {
            get {
                return ResourceManager.GetString("pocPostavkeJezikAplikacije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Početne postavke.
        /// </summary>
        public static string pocPostavkeNaslov {
            get {
                return ResourceManager.GetString("pocPostavkeNaslov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odabir prvenstva.
        /// </summary>
        public static string pocPostavkeOdabirPrvenstva {
            get {
                return ResourceManager.GetString("pocPostavkeOdabirPrvenstva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otvori aplikaciju.
        /// </summary>
        public static string pocPostavkeOtvoriAplikacijuButton {
            get {
                return ResourceManager.GetString("pocPostavkeOtvoriAplikacijuButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaz glavnog prozora.
        /// </summary>
        public static string pocPostavkePrikazGlavnogProzora {
            get {
                return ResourceManager.GetString("pocPostavkePrikazGlavnogProzora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postavke.
        /// </summary>
        public static string postavkeNaslov {
            get {
                return ResourceManager.GetString("postavkeNaslov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spremi postavke.
        /// </summary>
        public static string postavkeSpremiPostavke {
            get {
                return ResourceManager.GetString("postavkeSpremiPostavke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Golman.
        /// </summary>
        public static string pozicijaGolman {
            get {
                return ResourceManager.GetString("pozicijaGolman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napadač.
        /// </summary>
        public static string pozicijaNapadac {
            get {
                return ResourceManager.GetString("pozicijaNapadac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrambeni.
        /// </summary>
        public static string pozicijaObrambeni {
            get {
                return ResourceManager.GetString("pozicijaObrambeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vezni.
        /// </summary>
        public static string pozicijaVezni {
            get {
                return ResourceManager.GetString("pozicijaVezni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška u dohvaćanju podataka.
        /// </summary>
        public static string PregledReprezentacijeGreska {
            get {
                return ResourceManager.GetString("PregledReprezentacijeGreska", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Učitavam podatke....
        /// </summary>
        public static string PregledReprezentacijeInfoUcitavam {
            get {
                return ResourceManager.GetString("PregledReprezentacijeInfoUcitavam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled reprezentacija.
        /// </summary>
        public static string PregledReprezentacijeNaslov {
            get {
                return ResourceManager.GetString("PregledReprezentacijeNaslov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omiljena reprezentacija:.
        /// </summary>
        public static string PregledReprezentacijeOmiljenaReprezentacija {
            get {
                return ResourceManager.GetString("PregledReprezentacijeOmiljenaReprezentacija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postavke.
        /// </summary>
        public static string PregledReprezentacijePostavke {
            get {
                return ResourceManager.GetString("PregledReprezentacijePostavke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protivnik:.
        /// </summary>
        public static string PregledReprezentacijeProtivnik {
            get {
                return ResourceManager.GetString("PregledReprezentacijeProtivnik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatvaranje aplikacije.
        /// </summary>
        public static string PregledReprezentacijeZatvaranjeAplikacije {
            get {
                return ResourceManager.GetString("PregledReprezentacijeZatvaranjeAplikacije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cijeli zaslon.
        /// </summary>
        public static string rezolucijaFullscreen {
            get {
                return ResourceManager.GetString("rezolucijaFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mala.
        /// </summary>
        public static string rezolucijaMala {
            get {
                return ResourceManager.GetString("rezolucijaMala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Srednja.
        /// </summary>
        public static string rezolucijaSrednja {
            get {
                return ResourceManager.GetString("rezolucijaSrednja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velika.
        /// </summary>
        public static string rezolucijaVelika {
            get {
                return ResourceManager.GetString("rezolucijaVelika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muško.
        /// </summary>
        public static string spolMuski {
            get {
                return ResourceManager.GetString("spolMuski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žensko.
        /// </summary>
        public static string spolZenski {
            get {
                return ResourceManager.GetString("spolZenski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BROJ IGRAČA:.
        /// </summary>
        public static string StatIgracaBroj {
            get {
                return ResourceManager.GetString("StatIgracaBroj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOLOVI:.
        /// </summary>
        public static string StatIgracaGolovi {
            get {
                return ResourceManager.GetString("StatIgracaGolovi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAPETAN:.
        /// </summary>
        public static string StatIgracaKapetan {
            get {
                return ResourceManager.GetString("StatIgracaKapetan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistika igrača.
        /// </summary>
        public static string StatIgracaNaslov {
            get {
                return ResourceManager.GetString("StatIgracaNaslov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POZICIJA:.
        /// </summary>
        public static string StatIgracaPozicija {
            get {
                return ResourceManager.GetString("StatIgracaPozicija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ŽUTI KARTONI:.
        /// </summary>
        public static string StatIgracaZutiKartoni {
            get {
                return ResourceManager.GetString("StatIgracaZutiKartoni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIFA KOD:.
        /// </summary>
        public static string StatistikaReprezentacijeFifaKod {
            get {
                return ResourceManager.GetString("StatistikaReprezentacijeFifaKod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOL RAZLIKA:.
        /// </summary>
        public static string StatistikaReprezentacijeGolRazlika {
            get {
                return ResourceManager.GetString("StatistikaReprezentacijeGolRazlika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistika reprezentacije.
        /// </summary>
        public static string StatistikaReprezentacijeNaslov {
            get {
                return ResourceManager.GetString("StatistikaReprezentacijeNaslov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAZIV:.
        /// </summary>
        public static string StatistikaReprezentacijeNaziv {
            get {
                return ResourceManager.GetString("StatistikaReprezentacijeNaziv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEODLUČENO:.
        /// </summary>
        public static string StatistikaReprezentacijeNeodluceno {
            get {
                return ResourceManager.GetString("StatistikaReprezentacijeNeodluceno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POBJEDE:.
        /// </summary>
        public static string StatistikaReprezentacijePobjede {
            get {
                return ResourceManager.GetString("StatistikaReprezentacijePobjede", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PORAZI:.
        /// </summary>
        public static string StatistikaReprezentacijePorazi {
            get {
                return ResourceManager.GetString("StatistikaReprezentacijePorazi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRIMLJENI GOLOVI:.
        /// </summary>
        public static string StatistikaReprezentacijePrimljeniGolovi {
            get {
                return ResourceManager.GetString("StatistikaReprezentacijePrimljeniGolovi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ODIGRANE UTAKMICE:.
        /// </summary>
        public static string StatistikaReprezentacijeUtakmice {
            get {
                return ResourceManager.GetString("StatistikaReprezentacijeUtakmice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZABIJENI GOLOVI:.
        /// </summary>
        public static string StatistikaReprezentacijeZabijeniGolovi {
            get {
                return ResourceManager.GetString("StatistikaReprezentacijeZabijeniGolovi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap teren {
            get {
                object obj = ResourceManager.GetObject("teren", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odustani.
        /// </summary>
        public static string ZatvaranjeAplikacijeOdustani {
            get {
                return ResourceManager.GetString("ZatvaranjeAplikacijeOdustani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi.
        /// </summary>
        public static string ZatvaranjeAplikacijePotvrdi {
            get {
                return ResourceManager.GetString("ZatvaranjeAplikacijePotvrdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeste li sigurni?.
        /// </summary>
        public static string ZatvaranjeAplikacijeTekst {
            get {
                return ResourceManager.GetString("ZatvaranjeAplikacijeTekst", resourceCulture);
            }
        }
    }
}
