//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldCupWF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorldCupWF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Ball {
            get {
                object obj = ResourceManager.GetObject("Ball", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odustani.
        /// </summary>
        public static string ConfirmDialogBtnCancel {
            get {
                return ResourceManager.GetString("ConfirmDialogBtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi.
        /// </summary>
        public static string ConfirmDialogBtnOK {
            get {
                return ResourceManager.GetString("ConfirmDialogBtnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeste li sigurni?.
        /// </summary>
        public static string ConfirmDialogSadrzaj {
            get {
                return ResourceManager.GetString("ConfirmDialogSadrzaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška!.
        /// </summary>
        public static string izbaciGresku {
            get {
                return ResourceManager.GetString("izbaciGresku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj sliku.
        /// </summary>
        public static string OdabirOmiljenihDodajSliku {
            get {
                return ResourceManager.GetString("OdabirOmiljenihDodajSliku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slike|*.jpeg;*.jpg;*.png;|All files|*.*.
        /// </summary>
        public static string OdabirOmiljenihFilter {
            get {
                return ResourceManager.GetString("OdabirOmiljenihFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška u učitavanju igrača!.
        /// </summary>
        public static string OdabirOmiljenihGreska {
            get {
                return ResourceManager.GetString("OdabirOmiljenihGreska", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška u spremanju!.
        /// </summary>
        public static string OdabirOmiljenihGreskaUSpremanju {
            get {
                return ResourceManager.GetString("OdabirOmiljenihGreskaUSpremanju", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatvaranje aplikacije.
        /// </summary>
        public static string OdabirOmiljenihIgracaConfirmDialogNaslov {
            get {
                return ResourceManager.GetString("OdabirOmiljenihIgracaConfirmDialogNaslov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nije moguće selektirati više igrača, jer broj omiljenih igrača ne smije biti veći od 3.
        /// </summary>
        public static string OdabirOmiljenihIgracaDragAndDrop3Igraca {
            get {
                return ResourceManager.GetString("OdabirOmiljenihIgracaDragAndDrop3Igraca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nije moguće imati više od 3 omiljena igrača.
        /// </summary>
        public static string OdabirOmiljenihMax3Omiljena {
            get {
                return ResourceManager.GetString("OdabirOmiljenihMax3Omiljena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odabir omiljenih igrača.
        /// </summary>
        public static string OdabirOmiljenihNaslov {
            get {
                return ResourceManager.GetString("OdabirOmiljenihNaslov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omiljeni igrači.
        /// </summary>
        public static string OdabirOmiljenihOmiljeniIgraci {
            get {
                return ResourceManager.GetString("OdabirOmiljenihOmiljeniIgraci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostali igrači.
        /// </summary>
        public static string OdabirOmiljenihOstaliIgraci {
            get {
                return ResourceManager.GetString("OdabirOmiljenihOstaliIgraci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postavke.
        /// </summary>
        public static string OdabirOmiljenihPostavke {
            get {
                return ResourceManager.GetString("OdabirOmiljenihPostavke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prebacujem igrača....
        /// </summary>
        public static string OdabirOmiljenihPrebacujemIgraca {
            get {
                return ResourceManager.GetString("OdabirOmiljenihPrebacujemIgraca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premjesti.
        /// </summary>
        public static string OdabirOmiljenihPremjesti {
            get {
                return ResourceManager.GetString("OdabirOmiljenihPremjesti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistika....
        /// </summary>
        public static string OdabirOmiljenihStatistika {
            get {
                return ResourceManager.GetString("OdabirOmiljenihStatistika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gledatelja po utakmici.
        /// </summary>
        public static string OdabirOmiljenihStatistikaGledatelja {
            get {
                return ResourceManager.GetString("OdabirOmiljenihStatistikaGledatelja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Igrača.
        /// </summary>
        public static string OdabirOmiljenihStatistikaIgraca {
            get {
                return ResourceManager.GetString("OdabirOmiljenihStatistikaIgraca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Učitaj sliku....
        /// </summary>
        public static string OdabirOmiljenihUcitajSliku {
            get {
                return ResourceManager.GetString("OdabirOmiljenihUcitajSliku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odabir reprezentacije.
        /// </summary>
        public static string OdabirReprezentacijeNaslov {
            get {
                return ResourceManager.GetString("OdabirReprezentacijeNaslov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberi omiljenu reprezentaciju.
        /// </summary>
        public static string OdabirReprezentacijeOdaberiOmiljenu {
            get {
                return ResourceManager.GetString("OdabirReprezentacijeOdaberiOmiljenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omiljena reprezentacija:.
        /// </summary>
        public static string OdabirReprezentacijeOmiljena {
            get {
                return ResourceManager.GetString("OdabirReprezentacijeOmiljena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Učitavam postavke....
        /// </summary>
        public static string OdabirReprezentacijeUcitavamPostavke {
            get {
                return ResourceManager.GetString("OdabirReprezentacijeUcitavamPostavke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Početne postavke.
        /// </summary>
        public static string PocetnePostavkeNaslov {
            get {
                return ResourceManager.GetString("PocetnePostavkeNaslov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primjeni početne postavke.
        /// </summary>
        public static string PocetnePostavkePrimjeniPostavkeBtn {
            get {
                return ResourceManager.GetString("PocetnePostavkePrimjeniPostavkeBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi postavke.
        /// </summary>
        public static string PostavkeConfirmDialogNaslov {
            get {
                return ResourceManager.GetString("PostavkeConfirmDialogNaslov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engleski.
        /// </summary>
        public static string PostavkeEngleski {
            get {
                return ResourceManager.GetString("PostavkeEngleski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hrvatski.
        /// </summary>
        public static string PostavkeHrvatski {
            get {
                return ResourceManager.GetString("PostavkeHrvatski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muško.
        /// </summary>
        public static string PostavkeMusko {
            get {
                return ResourceManager.GetString("PostavkeMusko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postavke.
        /// </summary>
        public static string PostavkeNaslov {
            get {
                return ResourceManager.GetString("PostavkeNaslov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite jezik aplikacije:.
        /// </summary>
        public static string PostavkeOdabirJezika {
            get {
                return ResourceManager.GetString("PostavkeOdabirJezika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odabir prvenstva:.
        /// </summary>
        public static string PostavkeOdabirPrvenstva {
            get {
                return ResourceManager.GetString("PostavkeOdabirPrvenstva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molimo resetirajte aplikaciju.
        /// </summary>
        public static string PostavkePonovnoOtvoriApp {
            get {
                return ResourceManager.GetString("PostavkePonovnoOtvoriApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primjeni postavke.
        /// </summary>
        public static string PostavkePrimjeniPostavkeBtn {
            get {
                return ResourceManager.GetString("PostavkePrimjeniPostavkeBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žensko.
        /// </summary>
        public static string PostavkeZensko {
            get {
                return ResourceManager.GetString("PostavkeZensko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Golman.
        /// </summary>
        public static string pozicijaGolman {
            get {
                return ResourceManager.GetString("pozicijaGolman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napadač.
        /// </summary>
        public static string pozicijaNapadac {
            get {
                return ResourceManager.GetString("pozicijaNapadac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrambeni.
        /// </summary>
        public static string pozicijaObrambeni {
            get {
                return ResourceManager.GetString("pozicijaObrambeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veznjak.
        /// </summary>
        public static string pozicijaVezni {
            get {
                return ResourceManager.GetString("pozicijaVezni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RandomIgrac {
            get {
                object obj = ResourceManager.GetObject("RandomIgrac", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj posjetitelja.
        /// </summary>
        public static string StatistikaGledateljaBrojPosjetitelja {
            get {
                return ResourceManager.GetString("StatistikaGledateljaBrojPosjetitelja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dohvaćam podatke....
        /// </summary>
        public static string StatistikaGledateljaDohvacamPodatke {
            get {
                return ResourceManager.GetString("StatistikaGledateljaDohvacamPodatke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domaćin.
        /// </summary>
        public static string StatistikaGledateljaDomacin {
            get {
                return ResourceManager.GetString("StatistikaGledateljaDomacin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gost.
        /// </summary>
        public static string StatistikaGledateljaGost {
            get {
                return ResourceManager.GetString("StatistikaGledateljaGost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ispiši.
        /// </summary>
        public static string StatistikaGledateljaIspisi {
            get {
                return ResourceManager.GetString("StatistikaGledateljaIspisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokacija.
        /// </summary>
        public static string StatistikaGledateljaLokacija {
            get {
                return ResourceManager.GetString("StatistikaGledateljaLokacija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistika gledatelja po utakmici.
        /// </summary>
        public static string StatistikaGledateljaNaslov {
            get {
                return ResourceManager.GetString("StatistikaGledateljaNaslov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        public static string StatistikaIgracaIme {
            get {
                return ResourceManager.GetString("StatistikaIgracaIme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistika igrača.
        /// </summary>
        public static string StatistikaIgracaNaslov {
            get {
                return ResourceManager.GetString("StatistikaIgracaNaslov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogodci.
        /// </summary>
        public static string StatistikaIgracaPogodci {
            get {
                return ResourceManager.GetString("StatistikaIgracaPogodci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printanje je završilo!.
        /// </summary>
        public static string StatistikaIgracaPrintanje {
            get {
                return ResourceManager.GetString("StatistikaIgracaPrintanje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slika.
        /// </summary>
        public static string StatistikaIgracaSlika {
            get {
                return ResourceManager.GetString("StatistikaIgracaSlika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žuti kartoni.
        /// </summary>
        public static string StatistikaIgracaZutiKartoni {
            get {
                return ResourceManager.GetString("StatistikaIgracaZutiKartoni", resourceCulture);
            }
        }
    }
}
